"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.StatusCodes = void 0;
let StatusCodes = function (StatusCodes) {
  StatusCodes[StatusCodes["CONTINUE"] = 100] = "CONTINUE";
  StatusCodes[StatusCodes["SWITCHING_PROTOCOLS"] = 101] = "SWITCHING_PROTOCOLS";
  StatusCodes[StatusCodes["OK"] = 200] = "OK";
  StatusCodes[StatusCodes["CREATED"] = 201] = "CREATED";
  StatusCodes[StatusCodes["ACCEPTED"] = 202] = "ACCEPTED";
  StatusCodes[StatusCodes["NON_AUTHORITATIVE_INFORMATION"] = 203] = "NON_AUTHORITATIVE_INFORMATION";
  StatusCodes[StatusCodes["NO_CONTENT"] = 204] = "NO_CONTENT";
  StatusCodes[StatusCodes["RESET_CONTENT"] = 205] = "RESET_CONTENT";
  StatusCodes[StatusCodes["PARTIAL_CONTENT"] = 206] = "PARTIAL_CONTENT";
  StatusCodes[StatusCodes["MULTI_STATUS"] = 207] = "MULTI_STATUS";
  StatusCodes[StatusCodes["ALREADY_REPORTED"] = 208] = "ALREADY_REPORTED";
  StatusCodes[StatusCodes["IM_USED"] = 226] = "IM_USED";
  StatusCodes[StatusCodes["MULTIPLE_CHOICES"] = 300] = "MULTIPLE_CHOICES";
  StatusCodes[StatusCodes["MOVED_PERMANENTLY"] = 301] = "MOVED_PERMANENTLY";
  StatusCodes[StatusCodes["FOUND"] = 302] = "FOUND";
  StatusCodes[StatusCodes["SEE_OTHER"] = 303] = "SEE_OTHER";
  StatusCodes[StatusCodes["NOT_MODIFIED"] = 304] = "NOT_MODIFIED";
  StatusCodes[StatusCodes["USE_PROXY"] = 305] = "USE_PROXY";
  StatusCodes[StatusCodes["SWITCH_PROXY"] = 306] = "SWITCH_PROXY";
  StatusCodes[StatusCodes["TEMPORARY_REDIRECT"] = 307] = "TEMPORARY_REDIRECT";
  StatusCodes[StatusCodes["PERMANENT_REDIRECT"] = 308] = "PERMANENT_REDIRECT";
  StatusCodes[StatusCodes["BAD_REQUEST"] = 400] = "BAD_REQUEST";
  StatusCodes[StatusCodes["UNAUTHORIZED"] = 401] = "UNAUTHORIZED";
  StatusCodes[StatusCodes["PAYMENT_REQUIRED"] = 402] = "PAYMENT_REQUIRED";
  StatusCodes[StatusCodes["FORBIDDEN"] = 403] = "FORBIDDEN";
  StatusCodes[StatusCodes["NOT_FOUND"] = 404] = "NOT_FOUND";
  StatusCodes[StatusCodes["METHOD_NOT_ALLOWED"] = 405] = "METHOD_NOT_ALLOWED";
  StatusCodes[StatusCodes["NOT_ACCEPTABLE"] = 406] = "NOT_ACCEPTABLE";
  StatusCodes[StatusCodes["PROXY_AUTHENTICATION_REQUIRED"] = 407] = "PROXY_AUTHENTICATION_REQUIRED";
  StatusCodes[StatusCodes["REQUEST_TIMEOUT"] = 408] = "REQUEST_TIMEOUT";
  StatusCodes[StatusCodes["CONFLICT"] = 409] = "CONFLICT";
  StatusCodes[StatusCodes["GONE"] = 410] = "GONE";
  StatusCodes[StatusCodes["LENGTH_REQUIRED"] = 411] = "LENGTH_REQUIRED";
  StatusCodes[StatusCodes["PRECONDITION_FAILED"] = 412] = "PRECONDITION_FAILED";
  StatusCodes[StatusCodes["REQUEST_ENTITY_TOO_LARGE"] = 413] = "REQUEST_ENTITY_TOO_LARGE";
  StatusCodes[StatusCodes["REQUEST_URI_TOO_LONG"] = 414] = "REQUEST_URI_TOO_LONG";
  StatusCodes[StatusCodes["UNSUPPORTED_MEDIA_TYPE"] = 415] = "UNSUPPORTED_MEDIA_TYPE";
  StatusCodes[StatusCodes["REQUESTED_RANGE_NOT_SATISFIABLE"] = 416] = "REQUESTED_RANGE_NOT_SATISFIABLE";
  StatusCodes[StatusCodes["EXPECTATION_FAILED"] = 417] = "EXPECTATION_FAILED";
  StatusCodes[StatusCodes["IM_A_TEAPOT"] = 418] = "IM_A_TEAPOT";
  StatusCodes[StatusCodes["MISDIRECTED_REQUEST"] = 421] = "MISDIRECTED_REQUEST";
  StatusCodes[StatusCodes["UNPROCESSABLE_ENTITY"] = 422] = "UNPROCESSABLE_ENTITY";
  StatusCodes[StatusCodes["UPGRADE_REQUIRED"] = 426] = "UPGRADE_REQUIRED";
  StatusCodes[StatusCodes["PRECONDITION_REQUIRED"] = 428] = "PRECONDITION_REQUIRED";
  StatusCodes[StatusCodes["LOCKED"] = 423] = "LOCKED";
  StatusCodes[StatusCodes["FAILED_DEPENDENCY"] = 424] = "FAILED_DEPENDENCY";
  StatusCodes[StatusCodes["TOO_MANY_REQUESTS"] = 429] = "TOO_MANY_REQUESTS";
  StatusCodes[StatusCodes["REQUEST_HEADER_FIELDS_TOO_LARGE"] = 431] = "REQUEST_HEADER_FIELDS_TOO_LARGE";
  StatusCodes[StatusCodes["UNAVAILABLE_FOR_LEGAL_REASONS"] = 451] = "UNAVAILABLE_FOR_LEGAL_REASONS";
  StatusCodes[StatusCodes["INTERNAL_SERVER_ERROR"] = 500] = "INTERNAL_SERVER_ERROR";
  StatusCodes[StatusCodes["NOT_IMPLEMENTED"] = 501] = "NOT_IMPLEMENTED";
  StatusCodes[StatusCodes["BAD_GATEWAY"] = 502] = "BAD_GATEWAY";
  StatusCodes[StatusCodes["SERVICE_UNAVAILABLE"] = 503] = "SERVICE_UNAVAILABLE";
  StatusCodes[StatusCodes["GATEWAY_TIMEOUT"] = 504] = "GATEWAY_TIMEOUT";
  StatusCodes[StatusCodes["HTTP_VERSION_NOT_SUPPORTED"] = 505] = "HTTP_VERSION_NOT_SUPPORTED";
  StatusCodes[StatusCodes["VARIANT_ALSO_NEGOTIATES"] = 506] = "VARIANT_ALSO_NEGOTIATES";
  StatusCodes[StatusCodes["INSUFFICIENT_STORAGE"] = 507] = "INSUFFICIENT_STORAGE";
  StatusCodes[StatusCodes["LOOP_DETECTED"] = 508] = "LOOP_DETECTED";
  StatusCodes[StatusCodes["NOT_EXTENDED"] = 510] = "NOT_EXTENDED";
  StatusCodes[StatusCodes["NETWORK_AUTHENTICATION_REQUIRED"] = 511] = "NETWORK_AUTHENTICATION_REQUIRED";
  return StatusCodes;
}({});
exports.StatusCodes = StatusCodes;